---
title: "Data cleaning"
output: html_document
date: "`r Sys.Date()`"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Load data

```{r}
# raw data
raw <- readr::read_csv("data/ECAW_dataCut_221102.csv")
```

# Clean variable names

```{r}
raw <- janitor::clean_names(raw)
```

# Removing Qualtrics labels

```{r}
label <-
  raw%>% 
  slice(1:2)

raw <-
  raw %>% 
  slice(-(1:2))
```

# Creating a simple codebook

```{r}
codebook <-
  label %>% 
  slice(1) %>% 
  pivot_longer(cols = everything(), names_to = "original_var_name", values_to = "description") %>% 
  mutate(human_readable_var_name = case_when(
    original_var_name == "q3_1_1" ~ "typically_trustworthy",
    original_var_name == "q3_1_2" ~ "typically_reproducible",
    original_var_name == "q4_1_1" ~ "method_preregistered",
    original_var_name == "q4_1_2" ~ "method_blind",
    original_var_name == "q4_1_3" ~ "method_script",
    original_var_name == "q4_1_4" ~ "method_confirmatory",
    original_var_name == "q4_1_5" ~ "method_exploratory",
    original_var_name == "q8_1_1" ~ "ecaw_trustworthy",
    original_var_name == "q8_1_2" ~ "ecaw_reproducible",
    original_var_name == "q9_1_1" ~ "likert_less_willing",
    original_var_name == "q9_1_2" ~ "likert_opt_in",
    original_var_name == "q9_1_3" ~ "likert_study",
    original_var_name == "q9_1_4" ~ "likert_prefer_ecaw",
    original_var_name == "q10_3" ~ "contact",
    original_var_name == "q11_1_1" ~ "concerned",
    original_var_name == "q11_2" ~ "n_studies",
    original_var_name == "q11_3" ~ "programming_language",
    original_var_name == "q11_3_5_text" ~ "programming_language_other",
    TRUE ~ original_var_name
  ))

# Save the codebook
readr::write_tsv(codebook, "data/ECAW_raw_codebook.tsv")
```

# Variable renaming

```{r}
colnames(raw) <- dplyr::recode(
  colnames(raw), 
  !!!setNames(as.character(codebook$human_readable_var_name), codebook$original_var_name)
)
```

# Save clean daset

```{r}
readr::write_tsv(raw, "data/ECAW_raw_data.tsv")
```

