# Supplementary materials C

```{r numStudies, fig.cap="Caption goes here...", fig.align="center", out.width="100%", fig.width=6, fig.height=3.2}
# Create text for missing responses
n_studies_missing_text <- 
  processed %>% 
  filter(is.na(n_studies)) %>% 
  summarise(
    n = n(),
    missing_text = paste0("missing = ", n)
  ) %>% 
  pull(missing_text)

# Create histogram of the number of observational studies done
processed %>% 
  # Exclude missing responses
  filter(!is.na(n_studies)) %>% 
  ggplot() +
  aes(x = n_studies) +
  geom_histogram(binwidth = 3) +
  # annotate(geom = "text", x = 200, label = n_studies_missing_text, y = 30) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 30)) +
  labs(
    x = "Number of publications",
    y = "Number of respondents",
    title = "Approximately how many studies have you published using\na preexisting observational dataset (e.g., the ALSPAC dataset)?"
  ) +
  papaja::theme_apa()
  
# ggplot() +
#   geom_histogram(
#     data = dplyr::filter(valami, n_studies == 0),
#     mapping = aes(x = n_studies), binwidth = 1, color = 'red') +
#   geom_histogram(
#     data = dplyr::filter(valami, n_studies != 0),
#     mapping = aes(x = n_studies), binwidth = 5) +
#   # annotate(geom = "text", label = n_studies_missing_text, y = 30) +
#   scale_y_continuous(expand = c(0, 0), limits = c(0, 40)) +
#   labs(
#     x = "Number of observational studies done prior using ALSPAC",
#     y = "Count"
#   ) +
#   papaja::theme_apa()
```

```{r}
# Programming languages table
# We use the number of all participants who responded to the questionnaire as the denominator
denominator <- nrow(processed)

processed %>% 
  rename(lang = programming_language) %>% 
  separate_rows(lang, sep = ",") %>% 
  count(lang) %>% 
  replace_na(list(lang = "Missing")) %>% 
  # Removing irrelevant
  filter(lang != "irrelevant") %>% 
  ungroup() %>% 
  mutate(
    `Percentage of respondents` = round(n / denominator * 100, 0)
  ) %>% 
  arrange(desc(n)) %>% 
  rename(
    `Programming language` = lang,
    `N` = n
  ) %>% 
  kbl(
  .,
  format = "latex",
  col.names = c("Programming language", "N", "Percentage of respondents"),
  booktabs = T,
  escape = F,
  caption = "(ref:table1c-caption)",
  centering = T,
  position = "H") %>%
  kable_styling(full_width = F,  position = "left", latex_options = "scale_down") %>%
  row_spec(row = 0, bold = TRUE) %>%
  collapse_rows(columns = 1, valign = "top", latex_hline = "major", row_group_label_position = "identity")
```

(ref:table1c-caption) What programming language or software do you use for your analyses of preexisting observational data?

```{r concerned, warning=FALSE, fig.cap="Caption goes here...", fig.align="center", out.width="100%", fig.width=10, fig.height=4}
# Concerned figure data preparation
concerned_plot_data <-
  processed %>% 
  select(concerned) %>% 
  mutate(
    concerned = tolower(concerned),
    concerned = factor(concerned, levels = c(
      "very much less concerned",
      "less concerned",
      "somewhat less concerned",
      "as concerned as a typical researcher in my field",
      "somewhat more concerned",
      "more concerned",
      "very much more concerned"
      )
    )
  )

# Check distinct values in data
# distinct(concerned_plot_data, concerned)

# Create missing values text
concerned_missing_text <- 
  concerned_plot_data %>% 
  filter(is.na(concerned)) %>% 
  summarise(
    n = n(),
    missing_text = paste0("missing = ", n)
  ) %>% 
  pull(missing_text)

concerned_plot_data <- filter(concerned_plot_data, !is.na(concerned))

# Create likert package data not including the missing values
concerned_likert_plot_data <- likert(concerned_plot_data)

# Create figure
plot(concerned_likert_plot_data, digits = 1, text.size = 6, group.order = names(concerned_plot_data)) +
  scale_y_continuous(labels = c("100%", "50%", "0%", "50%", "100%"), limits = c(-105, 105)) +
  labs(title = "Compared to what you think of as a typical researcher who uses\npreexisting observational data in your field, how concerned\nare you with research trustworthiness, bias, rigour, and reproducibility ...") +
  theme(
    title = element_text(size = 14),
    axis.text.y = element_blank(),
    axis.text.x = element_text(size = 15),
    axis.title.x = element_blank(),
    legend.text = element_text(size = 10),
    legend.title = element_blank()
  )
```

